#this is a make file to create executable file from the code

all:
	gcc ./application_Module/main.c ./Server_Module/server.c ./Terminal_Module/terminal.c ./Card_Module/card.c -Wall -o app

clean:
	rm $(wildcard *.exe)